const API_BASE_URL = `${process.env.VUE_APP_BACKEND_URL}`;
const OPENVIDU_URL = `${process.env.VUE_APP_OPENVIDU_SERVER_URL}`;
const OPENVIIDU_SECRET =`${process.env.VUE_APP_OPENVIDU_SERVER_SECRET}`;
export { API_BASE_URL,OPENVIDU_URL,OPENVIIDU_SECRET };
